# Navn på itemflip inventory
inventory-name: "&e&lItem &6&lFlip"

# Liste af item types som gerne må blive bettet
item-whitelist:
  - "STONE"
  - "SKULL"
  - "REDSTONE_BLOCK"

# Max flips man må have igang (gælder både igangværende flips og flips man ikke har claimet)
max-flips: 5